// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Vs.AddMultipleProjectsToSolution
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAddMultipleProjectsCommandPackageString = "355a1959-c063-4587-a6df-65dc56b03054";
        public const string guidAddMultipleProjectsCommandPackageCmdSetString = "52eefd8b-3e82-4d3a-a15f-5ef227b118a9";
        public const string guidImagesString = "85147f92-f4ff-4a44-a2dc-af21971eb3c3";
        public static Guid guidAddMultipleProjectsCommandPackage = new Guid(guidAddMultipleProjectsCommandPackageString);
        public static Guid guidAddMultipleProjectsCommandPackageCmdSet = new Guid(guidAddMultipleProjectsCommandPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int SolutionContextAddItem = 0x1020;
        public const int AddMultipleProjectsSolutionContextCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
    }
}
